//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace TowqirAirSamples.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TestTEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TestTEntities object using the connection string found in the 'TestTEntities' section of the application configuration file.
        /// </summary>
        public TestTEntities() : base("name=TestTEntities", "TestTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TestTEntities object.
        /// </summary>
        public TestTEntities(string connectionString) : base(connectionString, "TestTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TestTEntities object.
        /// </summary>
        public TestTEntities(EntityConnection connection) : base(connection, "TestTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Table_1> Table_1
        {
            get
            {
                if ((_Table_1 == null))
                {
                    _Table_1 = base.CreateObjectSet<Table_1>("Table_1");
                }
                return _Table_1;
            }
        }
        private ObjectSet<Table_1> _Table_1;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<YearlyResult> YearlyResult
        {
            get
            {
                if ((_YearlyResult == null))
                {
                    _YearlyResult = base.CreateObjectSet<YearlyResult>("YearlyResult");
                }
                return _YearlyResult;
            }
        }
        private ObjectSet<YearlyResult> _YearlyResult;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MonthAverage> MonthAverage
        {
            get
            {
                if ((_MonthAverage == null))
                {
                    _MonthAverage = base.CreateObjectSet<MonthAverage>("MonthAverage");
                }
                return _MonthAverage;
            }
        }
        private ObjectSet<MonthAverage> _MonthAverage;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Table_1 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTable_1(Table_1 table_1)
        {
            base.AddObject("Table_1", table_1);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the YearlyResult EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToYearlyResult(YearlyResult yearlyResult)
        {
            base.AddObject("YearlyResult", yearlyResult);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MonthAverage EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMonthAverage(MonthAverage monthAverage)
        {
            base.AddObject("MonthAverage", monthAverage);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestTModel", Name="MonthAverage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MonthAverage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MonthAverage object.
        /// </summary>
        /// <param name="pKey">Initial value of the pKey property.</param>
        public static MonthAverage CreateMonthAverage(global::System.Int64 pKey)
        {
            MonthAverage monthAverage = new MonthAverage();
            monthAverage.pKey = pKey;
            return monthAverage;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 pKey
        {
            get
            {
                return _pKey;
            }
            set
            {
                if (_pKey != value)
                {
                    OnpKeyChanging(value);
                    ReportPropertyChanging("pKey");
                    _pKey = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pKey");
                    OnpKeyChanged();
                }
            }
        }
        private global::System.Int64 _pKey;
        partial void OnpKeyChanging(global::System.Int64 value);
        partial void OnpKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StationID
        {
            get
            {
                return _StationID;
            }
            set
            {
                OnStationIDChanging(value);
                ReportPropertyChanging("StationID");
                _StationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StationID");
                OnStationIDChanged();
            }
        }
        private Nullable<global::System.Int32> _StationID;
        partial void OnStationIDChanging(Nullable<global::System.Int32> value);
        partial void OnStationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RYear
        {
            get
            {
                return _RYear;
            }
            set
            {
                OnRYearChanging(value);
                ReportPropertyChanging("RYear");
                _RYear = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RYear");
                OnRYearChanged();
            }
        }
        private Nullable<global::System.Int32> _RYear;
        partial void OnRYearChanging(Nullable<global::System.Int32> value);
        partial void OnRYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_Jan
        {
            get
            {
                return _O3_Jan;
            }
            set
            {
                OnO3_JanChanging(value);
                ReportPropertyChanging("O3_Jan");
                _O3_Jan = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_Jan");
                OnO3_JanChanged();
            }
        }
        private Nullable<global::System.Decimal> _O3_Jan;
        partial void OnO3_JanChanging(Nullable<global::System.Decimal> value);
        partial void OnO3_JanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_Feb
        {
            get
            {
                return _O3_Feb;
            }
            set
            {
                OnO3_FebChanging(value);
                ReportPropertyChanging("O3_Feb");
                _O3_Feb = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_Feb");
                OnO3_FebChanged();
            }
        }
        private Nullable<global::System.Decimal> _O3_Feb;
        partial void OnO3_FebChanging(Nullable<global::System.Decimal> value);
        partial void OnO3_FebChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_Mar
        {
            get
            {
                return _O3_Mar;
            }
            set
            {
                OnO3_MarChanging(value);
                ReportPropertyChanging("O3_Mar");
                _O3_Mar = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_Mar");
                OnO3_MarChanged();
            }
        }
        private Nullable<global::System.Decimal> _O3_Mar;
        partial void OnO3_MarChanging(Nullable<global::System.Decimal> value);
        partial void OnO3_MarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_Apr
        {
            get
            {
                return _O3_Apr;
            }
            set
            {
                OnO3_AprChanging(value);
                ReportPropertyChanging("O3_Apr");
                _O3_Apr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_Apr");
                OnO3_AprChanged();
            }
        }
        private Nullable<global::System.Decimal> _O3_Apr;
        partial void OnO3_AprChanging(Nullable<global::System.Decimal> value);
        partial void OnO3_AprChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_May
        {
            get
            {
                return _O3_May;
            }
            set
            {
                OnO3_MayChanging(value);
                ReportPropertyChanging("O3_May");
                _O3_May = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_May");
                OnO3_MayChanged();
            }
        }
        private Nullable<global::System.Decimal> _O3_May;
        partial void OnO3_MayChanging(Nullable<global::System.Decimal> value);
        partial void OnO3_MayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_Jun
        {
            get
            {
                return _O3_Jun;
            }
            set
            {
                OnO3_JunChanging(value);
                ReportPropertyChanging("O3_Jun");
                _O3_Jun = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_Jun");
                OnO3_JunChanged();
            }
        }
        private Nullable<global::System.Decimal> _O3_Jun;
        partial void OnO3_JunChanging(Nullable<global::System.Decimal> value);
        partial void OnO3_JunChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_Jul
        {
            get
            {
                return _O3_Jul;
            }
            set
            {
                OnO3_JulChanging(value);
                ReportPropertyChanging("O3_Jul");
                _O3_Jul = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_Jul");
                OnO3_JulChanged();
            }
        }
        private Nullable<global::System.Decimal> _O3_Jul;
        partial void OnO3_JulChanging(Nullable<global::System.Decimal> value);
        partial void OnO3_JulChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_Aug
        {
            get
            {
                return _O3_Aug;
            }
            set
            {
                OnO3_AugChanging(value);
                ReportPropertyChanging("O3_Aug");
                _O3_Aug = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_Aug");
                OnO3_AugChanged();
            }
        }
        private Nullable<global::System.Decimal> _O3_Aug;
        partial void OnO3_AugChanging(Nullable<global::System.Decimal> value);
        partial void OnO3_AugChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_Sep
        {
            get
            {
                return _O3_Sep;
            }
            set
            {
                OnO3_SepChanging(value);
                ReportPropertyChanging("O3_Sep");
                _O3_Sep = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_Sep");
                OnO3_SepChanged();
            }
        }
        private Nullable<global::System.Decimal> _O3_Sep;
        partial void OnO3_SepChanging(Nullable<global::System.Decimal> value);
        partial void OnO3_SepChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_Oct
        {
            get
            {
                return _O3_Oct;
            }
            set
            {
                OnO3_OctChanging(value);
                ReportPropertyChanging("O3_Oct");
                _O3_Oct = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_Oct");
                OnO3_OctChanged();
            }
        }
        private Nullable<global::System.Decimal> _O3_Oct;
        partial void OnO3_OctChanging(Nullable<global::System.Decimal> value);
        partial void OnO3_OctChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_Nov
        {
            get
            {
                return _O3_Nov;
            }
            set
            {
                OnO3_NovChanging(value);
                ReportPropertyChanging("O3_Nov");
                _O3_Nov = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_Nov");
                OnO3_NovChanged();
            }
        }
        private Nullable<global::System.Decimal> _O3_Nov;
        partial void OnO3_NovChanging(Nullable<global::System.Decimal> value);
        partial void OnO3_NovChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_Dec
        {
            get
            {
                return _O3_Dec;
            }
            set
            {
                OnO3_DecChanging(value);
                ReportPropertyChanging("O3_Dec");
                _O3_Dec = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_Dec");
                OnO3_DecChanged();
            }
        }
        private Nullable<global::System.Decimal> _O3_Dec;
        partial void OnO3_DecChanging(Nullable<global::System.Decimal> value);
        partial void OnO3_DecChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_Jan
        {
            get
            {
                return _PM10_Jan;
            }
            set
            {
                OnPM10_JanChanging(value);
                ReportPropertyChanging("PM10_Jan");
                _PM10_Jan = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_Jan");
                OnPM10_JanChanged();
            }
        }
        private Nullable<global::System.Decimal> _PM10_Jan;
        partial void OnPM10_JanChanging(Nullable<global::System.Decimal> value);
        partial void OnPM10_JanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_Feb
        {
            get
            {
                return _PM10_Feb;
            }
            set
            {
                OnPM10_FebChanging(value);
                ReportPropertyChanging("PM10_Feb");
                _PM10_Feb = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_Feb");
                OnPM10_FebChanged();
            }
        }
        private Nullable<global::System.Decimal> _PM10_Feb;
        partial void OnPM10_FebChanging(Nullable<global::System.Decimal> value);
        partial void OnPM10_FebChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_Mar
        {
            get
            {
                return _PM10_Mar;
            }
            set
            {
                OnPM10_MarChanging(value);
                ReportPropertyChanging("PM10_Mar");
                _PM10_Mar = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_Mar");
                OnPM10_MarChanged();
            }
        }
        private Nullable<global::System.Decimal> _PM10_Mar;
        partial void OnPM10_MarChanging(Nullable<global::System.Decimal> value);
        partial void OnPM10_MarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_Apr
        {
            get
            {
                return _PM10_Apr;
            }
            set
            {
                OnPM10_AprChanging(value);
                ReportPropertyChanging("PM10_Apr");
                _PM10_Apr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_Apr");
                OnPM10_AprChanged();
            }
        }
        private Nullable<global::System.Decimal> _PM10_Apr;
        partial void OnPM10_AprChanging(Nullable<global::System.Decimal> value);
        partial void OnPM10_AprChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_May
        {
            get
            {
                return _PM10_May;
            }
            set
            {
                OnPM10_MayChanging(value);
                ReportPropertyChanging("PM10_May");
                _PM10_May = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_May");
                OnPM10_MayChanged();
            }
        }
        private Nullable<global::System.Decimal> _PM10_May;
        partial void OnPM10_MayChanging(Nullable<global::System.Decimal> value);
        partial void OnPM10_MayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_Jun
        {
            get
            {
                return _PM10_Jun;
            }
            set
            {
                OnPM10_JunChanging(value);
                ReportPropertyChanging("PM10_Jun");
                _PM10_Jun = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_Jun");
                OnPM10_JunChanged();
            }
        }
        private Nullable<global::System.Decimal> _PM10_Jun;
        partial void OnPM10_JunChanging(Nullable<global::System.Decimal> value);
        partial void OnPM10_JunChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_Jul
        {
            get
            {
                return _PM10_Jul;
            }
            set
            {
                OnPM10_JulChanging(value);
                ReportPropertyChanging("PM10_Jul");
                _PM10_Jul = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_Jul");
                OnPM10_JulChanged();
            }
        }
        private Nullable<global::System.Decimal> _PM10_Jul;
        partial void OnPM10_JulChanging(Nullable<global::System.Decimal> value);
        partial void OnPM10_JulChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_Aug
        {
            get
            {
                return _PM10_Aug;
            }
            set
            {
                OnPM10_AugChanging(value);
                ReportPropertyChanging("PM10_Aug");
                _PM10_Aug = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_Aug");
                OnPM10_AugChanged();
            }
        }
        private Nullable<global::System.Decimal> _PM10_Aug;
        partial void OnPM10_AugChanging(Nullable<global::System.Decimal> value);
        partial void OnPM10_AugChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_Sep
        {
            get
            {
                return _PM10_Sep;
            }
            set
            {
                OnPM10_SepChanging(value);
                ReportPropertyChanging("PM10_Sep");
                _PM10_Sep = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_Sep");
                OnPM10_SepChanged();
            }
        }
        private Nullable<global::System.Decimal> _PM10_Sep;
        partial void OnPM10_SepChanging(Nullable<global::System.Decimal> value);
        partial void OnPM10_SepChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_Oct
        {
            get
            {
                return _PM10_Oct;
            }
            set
            {
                OnPM10_OctChanging(value);
                ReportPropertyChanging("PM10_Oct");
                _PM10_Oct = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_Oct");
                OnPM10_OctChanged();
            }
        }
        private Nullable<global::System.Decimal> _PM10_Oct;
        partial void OnPM10_OctChanging(Nullable<global::System.Decimal> value);
        partial void OnPM10_OctChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_Nov
        {
            get
            {
                return _PM10_Nov;
            }
            set
            {
                OnPM10_NovChanging(value);
                ReportPropertyChanging("PM10_Nov");
                _PM10_Nov = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_Nov");
                OnPM10_NovChanged();
            }
        }
        private Nullable<global::System.Decimal> _PM10_Nov;
        partial void OnPM10_NovChanging(Nullable<global::System.Decimal> value);
        partial void OnPM10_NovChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_Dec
        {
            get
            {
                return _PM10_Dec;
            }
            set
            {
                OnPM10_DecChanging(value);
                ReportPropertyChanging("PM10_Dec");
                _PM10_Dec = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_Dec");
                OnPM10_DecChanged();
            }
        }
        private Nullable<global::System.Decimal> _PM10_Dec;
        partial void OnPM10_DecChanging(Nullable<global::System.Decimal> value);
        partial void OnPM10_DecChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestTModel", Name="Table_1")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Table_1 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Table_1 object.
        /// </summary>
        /// <param name="pKey">Initial value of the pKey property.</param>
        public static Table_1 CreateTable_1(global::System.Int64 pKey)
        {
            Table_1 table_1 = new Table_1();
            table_1.pKey = pKey;
            return table_1;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.String _Date;
        partial void OnDateChanging(global::System.String value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private global::System.String _Time;
        partial void OnTimeChanging(global::System.String value);
        partial void OnTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String O3
        {
            get
            {
                return _O3;
            }
            set
            {
                OnO3Changing(value);
                ReportPropertyChanging("O3");
                _O3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("O3");
                OnO3Changed();
            }
        }
        private global::System.String _O3;
        partial void OnO3Changing(global::System.String value);
        partial void OnO3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PM10
        {
            get
            {
                return _PM10;
            }
            set
            {
                OnPM10Changing(value);
                ReportPropertyChanging("PM10");
                _PM10 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PM10");
                OnPM10Changed();
            }
        }
        private global::System.String _PM10;
        partial void OnPM10Changing(global::System.String value);
        partial void OnPM10Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 pKey
        {
            get
            {
                return _pKey;
            }
            set
            {
                if (_pKey != value)
                {
                    OnpKeyChanging(value);
                    ReportPropertyChanging("pKey");
                    _pKey = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pKey");
                    OnpKeyChanged();
                }
            }
        }
        private global::System.Int64 _pKey;
        partial void OnpKeyChanging(global::System.Int64 value);
        partial void OnpKeyChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestTModel", Name="YearlyResult")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class YearlyResult : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new YearlyResult object.
        /// </summary>
        /// <param name="pKey">Initial value of the pKey property.</param>
        public static YearlyResult CreateYearlyResult(global::System.Int64 pKey)
        {
            YearlyResult yearlyResult = new YearlyResult();
            yearlyResult.pKey = pKey;
            return yearlyResult;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 pKey
        {
            get
            {
                return _pKey;
            }
            set
            {
                if (_pKey != value)
                {
                    OnpKeyChanging(value);
                    ReportPropertyChanging("pKey");
                    _pKey = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pKey");
                    OnpKeyChanged();
                }
            }
        }
        private global::System.Int64 _pKey;
        partial void OnpKeyChanging(global::System.Int64 value);
        partial void OnpKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StationID
        {
            get
            {
                return _StationID;
            }
            set
            {
                OnStationIDChanging(value);
                ReportPropertyChanging("StationID");
                _StationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StationID");
                OnStationIDChanged();
            }
        }
        private Nullable<global::System.Int32> _StationID;
        partial void OnStationIDChanging(Nullable<global::System.Int32> value);
        partial void OnStationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_2000
        {
            get
            {
                return _O3_2000;
            }
            set
            {
                OnO3_2000Changing(value);
                ReportPropertyChanging("O3_2000");
                _O3_2000 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_2000");
                OnO3_2000Changed();
            }
        }
        private Nullable<global::System.Decimal> _O3_2000;
        partial void OnO3_2000Changing(Nullable<global::System.Decimal> value);
        partial void OnO3_2000Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_2001
        {
            get
            {
                return _O3_2001;
            }
            set
            {
                OnO3_2001Changing(value);
                ReportPropertyChanging("O3_2001");
                _O3_2001 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_2001");
                OnO3_2001Changed();
            }
        }
        private Nullable<global::System.Decimal> _O3_2001;
        partial void OnO3_2001Changing(Nullable<global::System.Decimal> value);
        partial void OnO3_2001Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_2002
        {
            get
            {
                return _O3_2002;
            }
            set
            {
                OnO3_2002Changing(value);
                ReportPropertyChanging("O3_2002");
                _O3_2002 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_2002");
                OnO3_2002Changed();
            }
        }
        private Nullable<global::System.Decimal> _O3_2002;
        partial void OnO3_2002Changing(Nullable<global::System.Decimal> value);
        partial void OnO3_2002Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_2003
        {
            get
            {
                return _O3_2003;
            }
            set
            {
                OnO3_2003Changing(value);
                ReportPropertyChanging("O3_2003");
                _O3_2003 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_2003");
                OnO3_2003Changed();
            }
        }
        private Nullable<global::System.Decimal> _O3_2003;
        partial void OnO3_2003Changing(Nullable<global::System.Decimal> value);
        partial void OnO3_2003Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_2004
        {
            get
            {
                return _O3_2004;
            }
            set
            {
                OnO3_2004Changing(value);
                ReportPropertyChanging("O3_2004");
                _O3_2004 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_2004");
                OnO3_2004Changed();
            }
        }
        private Nullable<global::System.Decimal> _O3_2004;
        partial void OnO3_2004Changing(Nullable<global::System.Decimal> value);
        partial void OnO3_2004Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_2005
        {
            get
            {
                return _O3_2005;
            }
            set
            {
                OnO3_2005Changing(value);
                ReportPropertyChanging("O3_2005");
                _O3_2005 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_2005");
                OnO3_2005Changed();
            }
        }
        private Nullable<global::System.Decimal> _O3_2005;
        partial void OnO3_2005Changing(Nullable<global::System.Decimal> value);
        partial void OnO3_2005Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_2006
        {
            get
            {
                return _O3_2006;
            }
            set
            {
                OnO3_2006Changing(value);
                ReportPropertyChanging("O3_2006");
                _O3_2006 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_2006");
                OnO3_2006Changed();
            }
        }
        private Nullable<global::System.Decimal> _O3_2006;
        partial void OnO3_2006Changing(Nullable<global::System.Decimal> value);
        partial void OnO3_2006Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_2007
        {
            get
            {
                return _O3_2007;
            }
            set
            {
                OnO3_2007Changing(value);
                ReportPropertyChanging("O3_2007");
                _O3_2007 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_2007");
                OnO3_2007Changed();
            }
        }
        private Nullable<global::System.Decimal> _O3_2007;
        partial void OnO3_2007Changing(Nullable<global::System.Decimal> value);
        partial void OnO3_2007Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_2008
        {
            get
            {
                return _O3_2008;
            }
            set
            {
                OnO3_2008Changing(value);
                ReportPropertyChanging("O3_2008");
                _O3_2008 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_2008");
                OnO3_2008Changed();
            }
        }
        private Nullable<global::System.Decimal> _O3_2008;
        partial void OnO3_2008Changing(Nullable<global::System.Decimal> value);
        partial void OnO3_2008Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_2009
        {
            get
            {
                return _O3_2009;
            }
            set
            {
                OnO3_2009Changing(value);
                ReportPropertyChanging("O3_2009");
                _O3_2009 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_2009");
                OnO3_2009Changed();
            }
        }
        private Nullable<global::System.Decimal> _O3_2009;
        partial void OnO3_2009Changing(Nullable<global::System.Decimal> value);
        partial void OnO3_2009Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_2010
        {
            get
            {
                return _O3_2010;
            }
            set
            {
                OnO3_2010Changing(value);
                ReportPropertyChanging("O3_2010");
                _O3_2010 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_2010");
                OnO3_2010Changed();
            }
        }
        private Nullable<global::System.Decimal> _O3_2010;
        partial void OnO3_2010Changing(Nullable<global::System.Decimal> value);
        partial void OnO3_2010Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_2011
        {
            get
            {
                return _O3_2011;
            }
            set
            {
                OnO3_2011Changing(value);
                ReportPropertyChanging("O3_2011");
                _O3_2011 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_2011");
                OnO3_2011Changed();
            }
        }
        private Nullable<global::System.Decimal> _O3_2011;
        partial void OnO3_2011Changing(Nullable<global::System.Decimal> value);
        partial void OnO3_2011Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_2012
        {
            get
            {
                return _O3_2012;
            }
            set
            {
                OnO3_2012Changing(value);
                ReportPropertyChanging("O3_2012");
                _O3_2012 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_2012");
                OnO3_2012Changed();
            }
        }
        private Nullable<global::System.Decimal> _O3_2012;
        partial void OnO3_2012Changing(Nullable<global::System.Decimal> value);
        partial void OnO3_2012Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_2013
        {
            get
            {
                return _O3_2013;
            }
            set
            {
                OnO3_2013Changing(value);
                ReportPropertyChanging("O3_2013");
                _O3_2013 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_2013");
                OnO3_2013Changed();
            }
        }
        private Nullable<global::System.Decimal> _O3_2013;
        partial void OnO3_2013Changing(Nullable<global::System.Decimal> value);
        partial void OnO3_2013Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_2014
        {
            get
            {
                return _O3_2014;
            }
            set
            {
                OnO3_2014Changing(value);
                ReportPropertyChanging("O3_2014");
                _O3_2014 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_2014");
                OnO3_2014Changed();
            }
        }
        private Nullable<global::System.Decimal> _O3_2014;
        partial void OnO3_2014Changing(Nullable<global::System.Decimal> value);
        partial void OnO3_2014Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> O3_2015
        {
            get
            {
                return _O3_2015;
            }
            set
            {
                OnO3_2015Changing(value);
                ReportPropertyChanging("O3_2015");
                _O3_2015 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("O3_2015");
                OnO3_2015Changed();
            }
        }
        private Nullable<global::System.Decimal> _O3_2015;
        partial void OnO3_2015Changing(Nullable<global::System.Decimal> value);
        partial void OnO3_2015Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_2000
        {
            get
            {
                return _PM10_2000;
            }
            set
            {
                OnPM10_2000Changing(value);
                ReportPropertyChanging("PM10_2000");
                _PM10_2000 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_2000");
                OnPM10_2000Changed();
            }
        }
        private Nullable<global::System.Decimal> _PM10_2000;
        partial void OnPM10_2000Changing(Nullable<global::System.Decimal> value);
        partial void OnPM10_2000Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_2001
        {
            get
            {
                return _PM10_2001;
            }
            set
            {
                OnPM10_2001Changing(value);
                ReportPropertyChanging("PM10_2001");
                _PM10_2001 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_2001");
                OnPM10_2001Changed();
            }
        }
        private Nullable<global::System.Decimal> _PM10_2001;
        partial void OnPM10_2001Changing(Nullable<global::System.Decimal> value);
        partial void OnPM10_2001Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_2002
        {
            get
            {
                return _PM10_2002;
            }
            set
            {
                OnPM10_2002Changing(value);
                ReportPropertyChanging("PM10_2002");
                _PM10_2002 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_2002");
                OnPM10_2002Changed();
            }
        }
        private Nullable<global::System.Decimal> _PM10_2002;
        partial void OnPM10_2002Changing(Nullable<global::System.Decimal> value);
        partial void OnPM10_2002Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_2003
        {
            get
            {
                return _PM10_2003;
            }
            set
            {
                OnPM10_2003Changing(value);
                ReportPropertyChanging("PM10_2003");
                _PM10_2003 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_2003");
                OnPM10_2003Changed();
            }
        }
        private Nullable<global::System.Decimal> _PM10_2003;
        partial void OnPM10_2003Changing(Nullable<global::System.Decimal> value);
        partial void OnPM10_2003Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_2004
        {
            get
            {
                return _PM10_2004;
            }
            set
            {
                OnPM10_2004Changing(value);
                ReportPropertyChanging("PM10_2004");
                _PM10_2004 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_2004");
                OnPM10_2004Changed();
            }
        }
        private Nullable<global::System.Decimal> _PM10_2004;
        partial void OnPM10_2004Changing(Nullable<global::System.Decimal> value);
        partial void OnPM10_2004Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_2005
        {
            get
            {
                return _PM10_2005;
            }
            set
            {
                OnPM10_2005Changing(value);
                ReportPropertyChanging("PM10_2005");
                _PM10_2005 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_2005");
                OnPM10_2005Changed();
            }
        }
        private Nullable<global::System.Decimal> _PM10_2005;
        partial void OnPM10_2005Changing(Nullable<global::System.Decimal> value);
        partial void OnPM10_2005Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_2006
        {
            get
            {
                return _PM10_2006;
            }
            set
            {
                OnPM10_2006Changing(value);
                ReportPropertyChanging("PM10_2006");
                _PM10_2006 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_2006");
                OnPM10_2006Changed();
            }
        }
        private Nullable<global::System.Decimal> _PM10_2006;
        partial void OnPM10_2006Changing(Nullable<global::System.Decimal> value);
        partial void OnPM10_2006Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_2007
        {
            get
            {
                return _PM10_2007;
            }
            set
            {
                OnPM10_2007Changing(value);
                ReportPropertyChanging("PM10_2007");
                _PM10_2007 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_2007");
                OnPM10_2007Changed();
            }
        }
        private Nullable<global::System.Decimal> _PM10_2007;
        partial void OnPM10_2007Changing(Nullable<global::System.Decimal> value);
        partial void OnPM10_2007Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_2008
        {
            get
            {
                return _PM10_2008;
            }
            set
            {
                OnPM10_2008Changing(value);
                ReportPropertyChanging("PM10_2008");
                _PM10_2008 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_2008");
                OnPM10_2008Changed();
            }
        }
        private Nullable<global::System.Decimal> _PM10_2008;
        partial void OnPM10_2008Changing(Nullable<global::System.Decimal> value);
        partial void OnPM10_2008Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_2009
        {
            get
            {
                return _PM10_2009;
            }
            set
            {
                OnPM10_2009Changing(value);
                ReportPropertyChanging("PM10_2009");
                _PM10_2009 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_2009");
                OnPM10_2009Changed();
            }
        }
        private Nullable<global::System.Decimal> _PM10_2009;
        partial void OnPM10_2009Changing(Nullable<global::System.Decimal> value);
        partial void OnPM10_2009Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_2010
        {
            get
            {
                return _PM10_2010;
            }
            set
            {
                OnPM10_2010Changing(value);
                ReportPropertyChanging("PM10_2010");
                _PM10_2010 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_2010");
                OnPM10_2010Changed();
            }
        }
        private Nullable<global::System.Decimal> _PM10_2010;
        partial void OnPM10_2010Changing(Nullable<global::System.Decimal> value);
        partial void OnPM10_2010Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_2011
        {
            get
            {
                return _PM10_2011;
            }
            set
            {
                OnPM10_2011Changing(value);
                ReportPropertyChanging("PM10_2011");
                _PM10_2011 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_2011");
                OnPM10_2011Changed();
            }
        }
        private Nullable<global::System.Decimal> _PM10_2011;
        partial void OnPM10_2011Changing(Nullable<global::System.Decimal> value);
        partial void OnPM10_2011Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_2012
        {
            get
            {
                return _PM10_2012;
            }
            set
            {
                OnPM10_2012Changing(value);
                ReportPropertyChanging("PM10_2012");
                _PM10_2012 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_2012");
                OnPM10_2012Changed();
            }
        }
        private Nullable<global::System.Decimal> _PM10_2012;
        partial void OnPM10_2012Changing(Nullable<global::System.Decimal> value);
        partial void OnPM10_2012Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_2013
        {
            get
            {
                return _PM10_2013;
            }
            set
            {
                OnPM10_2013Changing(value);
                ReportPropertyChanging("PM10_2013");
                _PM10_2013 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_2013");
                OnPM10_2013Changed();
            }
        }
        private Nullable<global::System.Decimal> _PM10_2013;
        partial void OnPM10_2013Changing(Nullable<global::System.Decimal> value);
        partial void OnPM10_2013Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_2014
        {
            get
            {
                return _PM10_2014;
            }
            set
            {
                OnPM10_2014Changing(value);
                ReportPropertyChanging("PM10_2014");
                _PM10_2014 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_2014");
                OnPM10_2014Changed();
            }
        }
        private Nullable<global::System.Decimal> _PM10_2014;
        partial void OnPM10_2014Changing(Nullable<global::System.Decimal> value);
        partial void OnPM10_2014Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PM10_2015
        {
            get
            {
                return _PM10_2015;
            }
            set
            {
                OnPM10_2015Changing(value);
                ReportPropertyChanging("PM10_2015");
                _PM10_2015 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PM10_2015");
                OnPM10_2015Changed();
            }
        }
        private Nullable<global::System.Decimal> _PM10_2015;
        partial void OnPM10_2015Changing(Nullable<global::System.Decimal> value);
        partial void OnPM10_2015Changed();

        #endregion

    
    }

    #endregion

    
}
